headersOrigin = "config"
redirectsOrigin = "config"
plugins = []
functionsDirectory = "/home/tozzo/Downloads/dash/functions"
functionsDirectoryOrigin = "config"

[functions]

[functions."*"]

[build]
publish = "/home/tozzo/Downloads/dash/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "/home/tozzo/Downloads/dash/functions"

[build.environment]
NODE_VERSION = "18"
NODE_ENV = "production"
VITE_ENVIRONMENT = "production"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Content-Security-Policy = "default-src 'self'; script-src 'self' https://*.supabase.co; style-src 'self' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://*.supabase.co wss://*.supabase.co https://api.coingecko.com; frame-ancestors 'none';"

[[headers]]
for = "/assets/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*"

[headers.values]
Access-Control-Allow-Origin = "https://courageous-jelly-382fd9.netlify.app"
Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
Access-Control-Allow-Headers = "Content-Type, Authorization"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]